
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 35;
  public static final int DISPLAY = 2;
  public static final int DIVIDE = 27;
  public static final int LBRACKET = 42;
  public static final int DOUBLE = 7;
  public static final int NOTEQUAL = 33;
  public static final int LPAREN = 39;
  public static final int INT = 6;
  public static final int MINUS = 25;
  public static final int RPAREN = 40;
  public static final int STATIC = 10;
  public static final int SEMICOLON = 41;
  public static final int NOT = 29;
  public static final int AND = 31;
  public static final int LESSEQUAL = 36;
  public static final int LESSTHAN = 34;
  public static final int OR = 30;
  public static final int COMMA = 46;
  public static final int CLASS = 3;
  public static final int PLUS = 23;
  public static final int MAIN = 14;
  public static final int IF = 16;
  public static final int THIS = 12;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int RETURN = 19;
  public static final int DOUBLELITERAL = 49;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 32;
  public static final int TRUE = 20;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int BECOMES = 24;
  public static final int MOD = 28;
  public static final int VOID = 11;
  public static final int INTLITERAL = 48;
  public static final int GREATEREQUAL = 37;
  public static final int TIMES = 26;
  public static final int LBRACE = 44;
  public static final int ELSE = 17;
  public static final int WHILE = 18;
  public static final int PUBLIC = 9;
  public static final int RBRACE = 45;
  public static final int EXTENDS = 5;
  public static final int STRING = 13;
  public static final int FALSE = 21;
  public static final int PRINT = 22;
  public static final int LENGTH = 15;
  public static final int IDENTIFIER = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "CLASS",
  "NEW",
  "EXTENDS",
  "INT",
  "DOUBLE",
  "BOOLEAN",
  "PUBLIC",
  "STATIC",
  "VOID",
  "THIS",
  "STRING",
  "MAIN",
  "LENGTH",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "TRUE",
  "FALSE",
  "PRINT",
  "PLUS",
  "BECOMES",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "NOT",
  "OR",
  "AND",
  "EQUAL",
  "NOTEQUAL",
  "LESSTHAN",
  "GREATERTHAN",
  "LESSEQUAL",
  "GREATEREQUAL",
  "DOT",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "IDENTIFIER",
  "INTLITERAL",
  "DOUBLELITERAL"
  };
}

