
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 32;
  public static final int LPAREN = 29;
  public static final int INT = 6;
  public static final int MINUS = 24;
  public static final int STATIC = 9;
  public static final int RPAREN = 30;
  public static final int NOT = 26;
  public static final int SEMICOLON = 31;
  public static final int AND = 27;
  public static final int LESSTHAN = 28;
  public static final int COMMA = 36;
  public static final int CLASS = 3;
  public static final int DIGIT = 39;
  public static final int PLUS = 22;
  public static final int MAIN = 13;
  public static final int IF = 15;
  public static final int THIS = 11;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int RETURN = 18;
  public static final int RBRACKET = 33;
  public static final int TRUE = 19;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int BECOMES = 23;
  public static final int VOID = 10;
  public static final int TIMES = 25;
  public static final int LBRACE = 34;
  public static final int ELSE = 16;
  public static final int WHILE = 17;
  public static final int PUBLIC = 8;
  public static final int RBRACE = 35;
  public static final int EXTENDS = 5;
  public static final int STRING = 12;
  public static final int FALSE = 20;
  public static final int PRINT = 21;
  public static final int LENGTH = 14;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "CLASS",
  "NEW",
  "EXTENDS",
  "INT",
  "BOOLEAN",
  "PUBLIC",
  "STATIC",
  "VOID",
  "THIS",
  "STRING",
  "MAIN",
  "LENGTH",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "TRUE",
  "FALSE",
  "PRINT",
  "PLUS",
  "BECOMES",
  "MINUS",
  "TIMES",
  "NOT",
  "AND",
  "LESSTHAN",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "DOT",
  "IDENTIFIER",
  "DIGIT"
  };
}

