/* The following code was generated by JFlex 1.6.1 */

/**
 * JFlex specification for lexical analysis of a simple demo language.
 * Change this into the scanner for your implementation of MiniJava.
 *
 * CSE 401/M501/P501 18sp
 */


package Scanner;

import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.ComplexSymbolFactory.Location;
import Parser.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Scanner/minijava.jflex</tt>
 */
public final class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\3\1\63\1\63\1\3\22\0\1\4\1\45\3\0"+
    "\1\43\1\46\1\0\1\52\1\53\1\44\1\40\1\55\1\6\1\7"+
    "\1\42\12\2\1\0\1\54\1\50\1\41\1\51\2\0\3\1\1\10"+
    "\1\5\15\1\1\33\7\1\1\56\1\0\1\57\1\0\1\62\1\0"+
    "\1\16\1\30\1\20\1\11\1\22\1\37\1\35\1\32\1\12\2\1"+
    "\1\15\1\36\1\21\1\26\1\14\1\1\1\34\1\13\1\25\1\27"+
    "\1\31\1\23\1\24\1\17\1\1\1\60\1\47\1\61\7\0\1\63"+
    "\u1fa2\0\1\63\1\63\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\20\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\2\1\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\0\2\27\3\2\1\30\21\2\1\0\1\31"+
    "\1\32\1\33\1\34\1\35\1\27\1\0\2\2\1\36"+
    "\4\2\1\37\14\2\1\40\6\2\1\41\2\2\1\42"+
    "\1\43\1\2\1\44\3\2\1\45\6\2\1\46\1\2"+
    "\1\47\4\2\1\50\1\2\1\51\1\52\1\53\1\54"+
    "\3\2\1\55\1\56\1\57\1\60\1\61\13\0\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\64\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8"+
    "\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\64"+
    "\0\64\0\u0478\0\64\0\64\0\u04ac\0\u04e0\0\u0514\0\u0548"+
    "\0\u057c\0\64\0\64\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\u05b0\0\u05e4\0\64\0\u0618\0\u064c\0\u0680\0\150"+
    "\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820"+
    "\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\64\0\64\0\64\0\64\0\64\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\150\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8"+
    "\0\150\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34"+
    "\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\64\0\u0e6c\0\u0ea0"+
    "\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\150\0\u0fa4\0\u0fd8\0\150"+
    "\0\150\0\u100c\0\150\0\u1040\0\u1074\0\u10a8\0\150\0\u10dc"+
    "\0\u1110\0\u1144\0\u1178\0\u11ac\0\u11e0\0\150\0\u1214\0\150"+
    "\0\u1248\0\u127c\0\u12b0\0\u12e4\0\150\0\u1318\0\150\0\150"+
    "\0\150\0\150\0\u134c\0\u1380\0\u13b4\0\150\0\150\0\150"+
    "\0\150\0\150\0\u13e8\0\u141c\0\u1450\0\u1484\0\u14b8\0\u14ec"+
    "\0\u1520\0\u1554\0\u1588\0\u15bc\0\u15f0\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\3\1\6\1\7\1\3"+
    "\1\10\1\11\1\12\1\13\1\14\2\3\1\15\1\16"+
    "\1\17\1\20\1\3\1\21\2\3\1\22\1\23\1\3"+
    "\1\24\1\25\1\3\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\2"+
    "\66\0\2\3\2\0\1\3\2\0\30\3\22\0\1\3"+
    "\3\0\1\4\2\0\1\52\1\0\1\53\2\54\10\0"+
    "\1\52\44\0\2\5\61\0\1\53\62\0\2\3\2\0"+
    "\1\3\2\0\2\3\1\55\13\3\1\56\11\3\22\0"+
    "\1\3\2\0\2\3\2\0\1\3\2\0\11\3\1\57"+
    "\15\3\1\60\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\15\3\1\61\12\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\17\3\1\62\10\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\12\3\1\63\15\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\5\3"+
    "\1\64\22\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\12\3\1\65\15\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\5\3\1\66\6\3\1\67\13\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\22\3"+
    "\1\70\5\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\22\3\1\71\1\3\1\72\3\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\16\3\1\73\11\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\16\3"+
    "\1\74\11\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\7\3\1\75\5\3\1\76\12\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\12\3\1\77\15\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\6\3"+
    "\1\100\21\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\6\3\1\101\21\3\22\0\1\3\43\0\1\102"+
    "\62\0\1\103\70\0\1\104\64\0\1\105\55\0\1\106"+
    "\63\0\1\107\24\0\1\110\3\0\1\111\31\0\1\111"+
    "\25\0\1\53\2\0\1\52\2\0\2\54\10\0\1\52"+
    "\42\0\2\3\2\0\1\3\2\0\3\3\1\112\24\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\17\3"+
    "\1\113\10\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\15\3\1\114\12\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\6\3\1\115\21\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\20\3\1\116\7\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\11\3"+
    "\1\117\16\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\6\3\1\120\21\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\13\3\1\121\14\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\3\3\1\122\24\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\15\3"+
    "\1\123\12\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\2\3\1\124\25\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\2\3\1\125\25\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\17\3\1\126\10\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\16\3"+
    "\1\127\11\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\2\3\1\130\25\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\3\3\1\131\24\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\24\3\1\132\3\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\15\3"+
    "\1\133\12\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\2\3\1\134\25\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\5\3\1\135\22\3\22\0\1\3"+
    "\1\0\3\102\1\136\57\102\3\0\1\110\5\0\2\54"+
    "\54\0\1\110\62\0\2\3\2\0\1\3\2\0\4\3"+
    "\1\137\23\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\20\3\1\140\7\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\15\3\1\141\12\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\5\3\1\142\22\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\25\3"+
    "\1\143\2\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\3\3\1\144\24\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\12\3\1\145\15\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\12\3\1\146\15\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\5\3"+
    "\1\147\22\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\3\3\1\150\24\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\12\3\1\151\15\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\5\3\1\152\22\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\1\3"+
    "\1\153\26\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\15\3\1\154\12\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\2\3\1\155\25\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\17\3\1\156\10\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\11\3"+
    "\1\157\16\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\3\3\1\160\24\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\5\3\1\161\22\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\5\3\1\162\22\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\2\3"+
    "\1\163\25\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\2\3\1\164\25\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\15\3\1\165\12\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\3\3\1\166\24\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\11\3"+
    "\1\167\16\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\12\3\1\170\15\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\12\3\1\171\15\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\12\3\1\172\15\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\11\3"+
    "\1\173\16\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\24\3\1\174\3\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\12\3\1\175\15\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\6\3\1\176\21\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\12\3"+
    "\1\177\15\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\10\3\1\200\17\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\10\3\1\201\17\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\22\3\1\202\5\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\1\3"+
    "\1\203\26\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\6\3\1\204\21\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\26\3\1\205\1\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\25\3\1\206\2\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\2\0\11\3"+
    "\1\207\16\3\22\0\1\3\2\0\2\3\2\0\1\3"+
    "\2\0\7\3\1\210\20\3\22\0\1\3\2\0\2\3"+
    "\2\0\1\3\2\0\3\3\1\211\24\3\22\0\1\3"+
    "\2\0\2\3\2\0\1\3\2\0\11\3\1\212\16\3"+
    "\22\0\1\3\2\0\2\3\2\0\1\3\1\0\1\213"+
    "\30\3\22\0\1\3\27\0\1\214\64\0\1\215\61\0"+
    "\1\216\45\0\1\217\70\0\1\220\103\0\1\221\41\0"+
    "\1\222\72\0\1\223\67\0\1\224\53\0\1\225\67\0"+
    "\1\226\42\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5668];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\21\1\2\11\1\1\2\11"+
    "\5\1\10\11\1\0\1\1\1\11\25\1\1\0\5\11"+
    "\1\1\1\0\24\1\1\11\54\1\13\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  /** The CUP symbol factory, typically shared with parser. */
  private ComplexSymbolFactory symbolFactory = new ComplexSymbolFactory();

  /** Initialize scanner with input stream and a shared symbol factory. */
  public scanner(java.io.Reader in, ComplexSymbolFactory sf) {
    this(in);
    this.symbolFactory = sf;
  }

  /**
   * Construct a symbol with a given lexical token, a given
   * user-controlled datum, and the matched source location.
   *
   * @param code     identifier of the lexical token (i.e., sym.<TOKEN>)
   * @param value    user-controlled datum to associate with this symbol
   * @effects        constructs new ComplexSymbol via this.symbolFactory
   * @return         a fresh symbol storing the above-desribed information
   */
  private Symbol symbol(int code, Object value) {
    // Calculate symbol location
    int yylen = yylength();
    Location left = new Location(yyline + 1, yycolumn + 1, yychar);
    Location right = new Location(yyline + 1, yycolumn + yylen, yychar + yylen);
    // Calculate symbol name
    int max_code = sym.terminalNames.length;
    String name = code < max_code ? sym.terminalNames[code] : "<UNKNOWN(" + yytext() + ")>";
    return this.symbolFactory.newSymbol(name, code, left, right, value);
  }

  /**
   * Construct a symbol with a given lexical token and matched source
   * location, leaving the user-controlled value field uninitialized.
   *
   * @param code     identifier of the lexical token (i.e., sym.<TOKEN>)
   * @effects        constructs new ComplexSymbol via this.symbolFactory
   * @return         a fresh symbol storing the above-desribed information
   */
  private Symbol symbol(int code) {
    // Calculate symbol location
    int yylen = yylength();
    Location left = new Location(yyline + 1, yycolumn + 1, yychar);
    Location right = new Location(yyline + 1, yycolumn + yylen, yychar + yylen);
    // Calculate symbol name
    int max_code = sym.terminalNames.length;
    String name = code < max_code ? sym.terminalNames[code] : "<UNKNOWN(" + yytext() + ")>";
    return this.symbolFactory.newSymbol(name, code, left, right);
  }

  /**
   * Convert the symbol generated by this scanner into a string.
   *
   * This method is useful to include information in the string representation
   * in addition to the plain CUP name for a lexical token.
   *
   * @param symbol   symbol instance generated by this scanner
   * @return         string representation of the symbol
   */
   public String symbolToString(Symbol s) {
     // All symbols generated by this class are ComplexSymbol instances
     ComplexSymbol cs = (ComplexSymbol)s; 
     if (cs.sym == sym.IDENTIFIER) {
       return "ID(" + (String)cs.value + ")";
     } else if (cs.sym == sym.error) {
       return "<UNEXPECTED(" + (String)cs.value + ")>";
     } else {
       return cs.getName();
     }
   }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.printf(
      "%nUnexpected character '%s' on line %d at column %d of input.%n",
      yytext(), yyline + 1, yycolumn + 1
    );
    return symbol(sym.error, yytext());
            }
          case 51: break;
          case 2: 
            { return symbol(sym.IDENTIFIER, yytext());
            }
          case 52: break;
          case 3: 
            { return symbol(sym.INTLITERAL, yytext());
            }
          case 53: break;
          case 4: 
            { /* ignore whitespace */
            }
          case 54: break;
          case 5: 
            { return symbol(sym.MINUS);
            }
          case 55: break;
          case 6: 
            { return symbol(sym.DOT);
            }
          case 56: break;
          case 7: 
            { return symbol(sym.PLUS);
            }
          case 57: break;
          case 8: 
            { return symbol(sym.BECOMES);
            }
          case 58: break;
          case 9: 
            { return symbol(sym.DIVIDE);
            }
          case 59: break;
          case 10: 
            { return symbol(sym.MOD);
            }
          case 60: break;
          case 11: 
            { return symbol(sym.TIMES);
            }
          case 61: break;
          case 12: 
            { return symbol(sym.NOT);
            }
          case 62: break;
          case 13: 
            { return symbol(sym.LESSTHAN);
            }
          case 63: break;
          case 14: 
            { return symbol(sym.GREATERTHAN);
            }
          case 64: break;
          case 15: 
            { return symbol(sym.LPAREN);
            }
          case 65: break;
          case 16: 
            { return symbol(sym.RPAREN);
            }
          case 66: break;
          case 17: 
            { return symbol(sym.SEMICOLON);
            }
          case 67: break;
          case 18: 
            { return symbol(sym.COMMA);
            }
          case 68: break;
          case 19: 
            { return symbol(sym.RBRACKET);
            }
          case 69: break;
          case 20: 
            { return symbol(sym.LBRACKET);
            }
          case 70: break;
          case 21: 
            { return symbol(sym.LBRACE);
            }
          case 71: break;
          case 22: 
            { return symbol(sym.RBRACE);
            }
          case 72: break;
          case 23: 
            { return symbol(sym.DOUBLELITERAL, yytext());
            }
          case 73: break;
          case 24: 
            { return symbol(sym.IF);
            }
          case 74: break;
          case 25: 
            { return symbol(sym.NOTEQUAL);
            }
          case 75: break;
          case 26: 
            { return symbol(sym.AND);
            }
          case 76: break;
          case 27: 
            { return symbol(sym.OR);
            }
          case 77: break;
          case 28: 
            { return symbol(sym.LESSEQUAL);
            }
          case 78: break;
          case 29: 
            { return symbol(sym.GREATEREQUAL);
            }
          case 79: break;
          case 30: 
            { return symbol(sym.INT);
            }
          case 80: break;
          case 31: 
            { return symbol(sym.NEW);
            }
          case 81: break;
          case 32: 
            { /* ignore comments */
            }
          case 82: break;
          case 33: 
            { return symbol(sym.ELSE);
            }
          case 83: break;
          case 34: 
            { return symbol(sym.THIS);
            }
          case 84: break;
          case 35: 
            { return symbol(sym.TRUE);
            }
          case 85: break;
          case 36: 
            { return symbol(sym.VOID);
            }
          case 86: break;
          case 37: 
            { return symbol(sym.MAIN);
            }
          case 87: break;
          case 38: 
            { return symbol(sym.CLASS);
            }
          case 88: break;
          case 39: 
            { return symbol(sym.WHILE);
            }
          case 89: break;
          case 40: 
            { return symbol(sym.FALSE);
            }
          case 90: break;
          case 41: 
            { return symbol(sym.DOUBLE);
            }
          case 91: break;
          case 42: 
            { return symbol(sym.STATIC);
            }
          case 92: break;
          case 43: 
            { return symbol(sym.PUBLIC);
            }
          case 93: break;
          case 44: 
            { return symbol(sym.LENGTH);
            }
          case 94: break;
          case 45: 
            { return symbol(sym.STRING);
            }
          case 95: break;
          case 46: 
            { return symbol(sym.RETURN);
            }
          case 96: break;
          case 47: 
            { return symbol(sym.DISPLAY);
            }
          case 97: break;
          case 48: 
            { return symbol(sym.EXTENDS);
            }
          case 98: break;
          case 49: 
            { return symbol(sym.BOOLEAN);
            }
          case 99: break;
          case 50: 
            { return symbol(sym.PRINT);
            }
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
